/* In-depth entries, written for this site. Every quote was checked against the page it is attributed to.
   Each strand is marked: established (supported by the official record), contested (credible people disagree),
   or not supported by the record (a claim in circulation the record does not bear out). */
import type { Controversy } from './controversies';

export const UK_DISPUTES: Controversy[] = [
  {
    id: 'rayner-stamp-duty', featured: true, date: '2026-05-14', type: 'conduct', category: 'Ministers’ conduct',
    title: 'The Deputy Prime Minister who resigned over stamp duty, then was cleared by HMRC',
    minister: 'Angela Rayner', portfolio: 'then Deputy Prime Minister and Housing Secretary',
    summary: 'In September 2025 Angela Rayner admitted underpaying about £40,000 of stamp duty on an £800,000 flat in Hove, bought in May 2025 through arrangements involving a trust for her disabled son. The Prime Minister’s Independent Adviser on Ministerial Standards found she had breached the Ministerial Code, while accepting she had acted in good faith, and she resigned from all her posts. Eight months later HMRC concluded its own investigation and cleared her, with no penalty.',
    points: [
      { heading: 'What the ethics adviser found', standing: 'established',
        body: 'The Independent Adviser on Ministerial Standards examined the case on 3 September 2025 and concluded that she had not met the highest standards of proper conduct required by the Ministerial Code, while accepting that she had acted in good faith on the advice she had. She resigned as Deputy Prime Minister, Housing Secretary and Deputy Leader of the Labour Party on 5 September 2025 and paid the outstanding tax.',
        sources: [{ title: 'Independent Adviser on Ministerial Standards: annual report 2025–26', url: 'https://www.gov.uk/government/publications/independent-adviser-on-ministerial-standards-annual-report-2025-2026/independent-adviser-on-ministerial-standards-annual-report-2025-2026-html' },
                  { title: 'Letter from the Independent Adviser and the exchange of letters with the Prime Minister', url: 'https://www.gov.uk/government/publications/letter-from-the-independent-adviser-on-ministerial-standards-exchange-of-letters-between-the-prime-minister-and-angela-rayner-mp' }] },
      { heading: 'What the tax authority found', standing: 'established',
        body: 'On 14 May 2026 Rayner said HMRC had completed its investigation and cleared her of wrongdoing, with no fine or penalty. She said she had been “horrified” at the suggestion she had not paid the right tax and “welcomed” the finding. The two outcomes are not contradictory: the ethics adviser was judging conduct against the Ministerial Code, while HMRC was deciding whether the underpayment was careless or deliberate.',
        sources: [{ title: 'ITV News: Angela Rayner cleared by HMRC after stamp duty row, 14 May 2026', url: 'https://www.itv.com/news/2026-05-14/angela-rayner-says-she-has-been-cleared-by-hmrc-after-stamp-duty-row' }] },
    ],
    response: 'Rayner apologised at the time, referred herself to the Independent Adviser, accepted the finding and resigned. After the HMRC decision she said she welcomed being cleared and that she had always intended to pay the correct amount.',
    outcome: 'Resigned from government in September 2025. Cleared by HMRC in May 2026 with no penalty, having paid the tax owed.',
    status: 'resolved',
    sources: [{ title: 'Independent Adviser on Ministerial Standards: annual report 2025–26', url: 'https://www.gov.uk/government/publications/independent-adviser-on-ministerial-standards-annual-report-2025-2026/independent-adviser-on-ministerial-standards-annual-report-2025-2026-html' }],
    verified_on: '2026-09-21',
  },
  {
    id: 'winter-fuel-payment', featured: true, date: '2025-06-09', type: 'policy', category: 'Welfare',
    title: 'Winter fuel payments: taken from ten million pensioners, then partly given back',
    minister: 'Rachel Reeves', portfolio: 'then Chancellor of the Exchequer',
    summary: 'One of the new government’s first decisions, in July 2024, was to restrict the winter fuel payment to pensioners on pension credit, removing it from around ten million people and saving roughly £1.8 billion a year. After sustained criticism and heavy local election losses, the government reversed much of it in June 2025, restoring the payment to pensioners with incomes up to £35,000 and clawing it back through the tax system above that. The reversal cost about £1.25 billion of the original saving.',
    points: [
      { heading: 'What was decided and what it saved', standing: 'established',
        body: 'The payment, worth £200 to £300 a year, was restricted to those receiving pension credit and certain other benefits from winter 2024–25. The Treasury put the saving at about £1.8 billion a year. Around ten million pensioners who had previously received it no longer did.',
        sources: [{ title: 'House of Commons Library: Winter Fuel Payment', url: 'https://commonslibrary.parliament.uk/research-briefings/cbp-10108/' }] },
      { heading: 'The reversal', standing: 'established',
        body: 'On 9 June 2025 the government announced that the payment would be restored to pensioners with an income of £35,000 or less, with the money recovered through HMRC from those above the threshold. The Chancellor had said days earlier that “the means test will increase and more people will get a winter fuel payment this winter”. Most of the original saving was given up.',
        sources: [{ title: 'House of Commons Library: Winter Fuel Payment', url: 'https://commonslibrary.parliament.uk/research-briefings/cbp-10108/' }] },
      { heading: 'Whether it cost pensioners their lives or their votes', standing: 'contested',
        body: 'Critics, including Age UK and opposition parties, argued the cut would push vulnerable pensioners into cold homes; supporters argued a universal payment to millionaire pensioners was indefensible when public finances were tight. Claims about excess winter deaths caused specifically by the change have not been established by any official analysis. What is not in dispute is the political cost: the decision is widely cited, including by Labour figures, as a significant factor in the party’s losses at the May 2026 local elections and in the change of Prime Minister that followed.',
        sources: [{ title: 'House of Commons Library: Winter Fuel Payment', url: 'https://commonslibrary.parliament.uk/research-briefings/cbp-10108/' }] },
    ],
    response: 'The government argued the decision was forced by the state of the public finances it inherited, and that pension credit take-up campaigns would protect the poorest. On reversing it, ministers said the public finances had improved enough to allow a more generous means test.',
    outcome: 'Partly reversed from winter 2025–26. Pensioners with incomes up to £35,000 receive the payment; it is recovered through the tax system above that.',
    status: 'resolved',
    sources: [{ title: 'House of Commons Library: Winter Fuel Payment', url: 'https://commonslibrary.parliament.uk/research-briefings/cbp-10108/' }],
    verified_on: '2026-09-21',
  },
  {
    id: 'chagos-cost', featured: true, date: '2025-05-22', type: 'policy', category: 'Defence and foreign policy',
    title: 'The Chagos deal: is the bill £3.4 billion or £35 billion?',
    minister: 'Sir Keir Starmer', portfolio: 'then Prime Minister',
    summary: 'In May 2025 the UK signed a treaty ceding sovereignty of the Chagos Islands to Mauritius while leasing back the Diego Garcia military base for 99 years. The two sides of the argument use figures that differ almost tenfold, and both are arithmetically defensible: the difference is whether future payments are discounted to today’s money.',
    points: [
      { heading: 'The government’s figure', standing: 'established',
        body: 'The government says the deal averages £101 million a year in 2025–26 prices, giving a net present value of about £3.4 billion over 99 years, plus a £40 million trust fund for Chagossians. The Government Actuary’s Department verified the calculation. Net present value is the standard Treasury way of valuing payments spread over decades.',
        sources: [{ title: 'House of Commons Library: the UK–Mauritius agreement on the Chagos Archipelago', url: 'https://commonslibrary.parliament.uk/research-briefings/cbp-10273/' }] },
      { heading: 'The opposition’s figure', standing: 'contested',
        body: 'The Conservatives cite about £35 billion, which is the sum of the cash payments over 99 years without discounting and with inflation uprating. Neither figure is invented; they answer different questions. The shadow defence minister complained to the UK Statistics Authority, which agreed that describing £3.4 billion as the “net cost” without explaining the discounting risked misleading people, but did not rule either number wrong.',
        sources: [{ title: 'Full Fact: what is the true cost of the Chagos deal?', url: 'https://fullfact.org/politics/chagos-deal-true-cost/' },
                  { title: 'House of Commons Library: the UK–Mauritius agreement on the Chagos Archipelago', url: 'https://commonslibrary.parliament.uk/research-briefings/cbp-10273/' }] },
    ],
    response: 'The government says the deal was necessary to secure the long-term legal basis of the Diego Garcia base, that it was supported by the United States, and that the cost is a fraction of the base’s strategic value.',
    outcome: 'The treaty was signed on 22 May 2025. The dispute over how to describe its cost continues, and the UK Statistics Authority has criticised the presentation without endorsing either figure.',
    status: 'ongoing',
    sources: [{ title: 'House of Commons Library: the UK–Mauritius agreement on the Chagos Archipelago', url: 'https://commonslibrary.parliament.uk/research-briefings/cbp-10273/' }],
    verified_on: '2026-09-21',
  },
  {
    id: 'employer-nics', featured: true, date: '2025-04-06', type: 'policy', category: 'Tax and jobs',
    title: 'The employers’ National Insurance rise: who actually paid for it?',
    minister: 'Rachel Reeves', portfolio: 'then Chancellor of the Exchequer',
    summary: 'The October 2024 Budget raised employers’ National Insurance from 13.8% to 15% and cut the threshold at which employers start paying from £9,100 to £5,000, effective April 2025. The government said it kept the manifesto promise not to raise taxes on “working people” because the rates paid by employees were untouched. Critics said the cost would fall on workers anyway, through lower pay and fewer jobs.',
    points: [
      { heading: 'What the official forecaster expected', standing: 'established',
        body: 'The Office for Budget Responsibility expected most of the cost to be passed on to workers through lower wages, and forecast a reduction in labour supply of roughly 0.2%, equivalent to a little over 50,000 average-hours jobs by 2029–30.',
        sources: [{ title: 'House of Commons Library: employer National Insurance contributions', url: 'https://commonslibrary.parliament.uk/research-briefings/cbp-10189/' }] },
      { heading: 'What has happened since', standing: 'contested',
        body: 'The number of payrolled employees fell by roughly 96,000 to 109,000 over the year to January 2026, depending on the vintage of the estimate. How much of that is due to National Insurance is genuinely disputed: the National Living Wage rose at the same time, interest rates were high, and payroll estimates are revised. Business groups attribute the fall largely to the tax; others point to the wider economy.',
        sources: [{ title: 'House of Commons Library: employer National Insurance contributions', url: 'https://commonslibrary.parliament.uk/research-briefings/cbp-10189/' }] },
      { heading: 'Whether the “working people” promise was kept', standing: 'contested',
        body: 'On a literal reading the promise held: the rates of income tax, employee National Insurance and VAT were not raised. Against that, the OBR’s own expectation is that employees bear most of the cost through lower wages, and the freeze on income tax thresholds, extended to 2031 in the November 2025 Budget, pulls more people into higher tax bands without any rate changing. Whether that counts as a tax rise on working people is a question of wording, not of arithmetic.',
        sources: [{ title: 'House of Commons Library: employer National Insurance contributions', url: 'https://commonslibrary.parliament.uk/research-briefings/cbp-10189/' }] },
    ],
    response: 'The government says it protected the smallest employers by raising the employment allowance, that it did not raise the taxes people see on their payslips, and that the money funds the NHS and public services.',
    outcome: 'The rise took effect in April 2025 and remains in place.',
    status: 'ongoing',
    sources: [{ title: 'House of Commons Library: employer National Insurance contributions', url: 'https://commonslibrary.parliament.uk/research-briefings/cbp-10189/' }],
    verified_on: '2026-09-21',
  },
  {
    id: 'millionaire-exodus', date: '2026-01-01', type: 'policy', category: 'Tax',
    title: 'The “millionaire exodus”: a widely repeated figure that fell apart',
    minister: '', portfolio: '',
    summary: 'After the abolition of the non-domiciled tax status, widely reported research claimed that around 16,500 millionaires would leave the UK in a single year, and the figure was repeated in thousands of news articles. The firm behind it later dropped both the researcher and the numbers, and the official data does not support the claim.',
    points: [
      { heading: 'What the record shows', standing: 'unverified',
        body: 'The widely quoted estimate was built largely from the locations people state on LinkedIn, not from residence or tax records. The firm that published it subsequently withdrew the figures and parted company with the researcher. A 2026 HMRC review found the non-dom population fell by about 0.5%, and roughly 9,000 left in 2024–25 compared with 11,200 the previous year: fewer departures than the year before, not a stampede. There has been movement, and the long-run revenue effect is genuinely uncertain, but the headline number that drove the debate does not stand up.',
        sources: [{ title: 'Tax Justice Network: millionaire exodus study drops author and numbers', url: 'https://taxjustice.net/press/millionaire-exodus-study-drops-author-and-numbers-after-fake-data-accusations/' },
                  { title: 'The Conversation: millionaires may not be fleeing the UK in droves', url: 'https://theconversation.com/millionaires-may-not-be-fleeing-the-uk-in-droves-but-there-are-reasons-these-stories-persist-259591' }] },
    ],
    response: 'The government says the non-dom regime was an unjustifiable loophole and that its replacement raises revenue while keeping the UK competitive for genuine investment.',
    outcome: 'The claim is still repeated. It is included here because a figure being widely quoted is not the same as it being true, whichever side it helps.',
    status: 'no-finding',
    sources: [{ title: 'Tax Justice Network: millionaire exodus study drops author and numbers', url: 'https://taxjustice.net/press/millionaire-exodus-study-drops-author-and-numbers-after-fake-data-accusations/' }],
    verified_on: '2026-09-21',
  },
];
